steps:
  # === STEP 0: Build Docker Image ===
  - id: Build-docker
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/production/kelompok1:$SHORT_SHA
      - .
    timeout: 900s

  # === STEP 1: Push Docker Image ===
  - id: Push-docker
    name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/production/kelompok1:$SHORT_SHA
    timeout: 900s

  # === STEP 2: envsubst via shell ===
  - id: envSubst-for-deployment.yml
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    env:
      - SHORT_SHA=$SHORT_SHA
      - PROJECT_ID=$PROJECT_ID
    args:
      - "-c"
      - |
        echo "🔧 Rendering deployment.yaml dengan envsubst..."
        envsubst < deployment.yaml > deployment_rendered.yaml
        echo "✔ Selesai membuat deployment_rendered.yaml"

  # === STEP 3: Deploy to GKE ===
  - id: Deploy-to-GKE
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment_rendered.yaml
      - --cluster=kelompok1-production
      - --location=asia-southeast2-a
    timeout: 900s

# ===== KONFIGURASI GLOBAL =====

timeout: "3600s"

options:
  logging: CLOUD_LOGGING_ONLY

service_account: "SERVICE_ACCOUNT_KAMU@kelompok1-480205.iam.gserviceaccount.com"
