steps:
  # === STEP 0: Build Docker Image ===
  - id: Build-docker
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/production/kelompok1:$SHORT_SHA
      - .
    timeout: 900s

  # === STEP 1: Push Docker Image ===
  - id: Push-docker
    name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/production/kelompok1:$SHORT_SHA
    timeout: 900s

  # === STEP 2: envsubst untuk deployment.yaml ===
  - id: envSubst-for-deployment
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
          echo "🔧 Rendering deployment.yaml..."
          export PROJECT_ID="$PROJECT_ID"
          export SHORT_SHA="$SHORT_SHA"
          envsubst < deployment.yaml > deployment_rendered.yaml
          echo "✔ Selesai membuat deployment_rendered.yaml"
          echo "====== OUTPUT ======"
          cat deployment_rendered.yaml
          echo "===================="

  # === STEP 3: Deploy ke GKE ===
  - id: Deploy-to-GKE
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment_rendered.yaml
      - --cluster=clusterkelompok1
      - --location=asia-southeast2-a
    timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "3600s"

service_account: "SERVICE_ACCOUNT_KAMU@kelompok1-480205.iam.gserviceaccount.com"
